#!/bin/bash
# usage: 03 path_to_directory

# Check the number of arguments

if (( $# != 1 )) ; then
	echo "usage: bash $0 path_to_directory"
	exit 1
fi

# Check if the path leads to an existing directory

if [[ ! -d "$1" ]] ; then
	echo "The directory doesn't exist"
	exit 1
fi

# Check if the directory is a git repository

cd "$1"
git rev-parse --is-inside-work-tree &> /dev/null
if (( $? != 0 )) ; then
	echo "The directory is not a Git repository"
	exit 1
fi

# Check if git add or git commit needs to be used 

prompt=$(git status --porcelain)
if [[ $prompt != "" ]] ; then
	git add -A
	read -p "Please enter the commit message : " message
	git commit -am "$message"
else
	echo "Nothing to add or commit"
fi

# Git push

git push origin master
