#!/bin/bash
# usage: 03 path_to_directory

# Check the number of arguments

if (( $# != 1 )) ; then
	echo "usage: bash $0 path_to_directory"
	exit 1
fi

# Check if the path leads to an existing directory

if [[ ! -d "$1" ]] ; then
	echo "The directory doesn't exist"
	exit 1
fi

# Check if the directory is a git repository

if ! ls -a $1 | grep ".git" > /dev/null ; then
	echo "The directory is not a Git repository"
	exit 1
fi

# Git commands

cd "$1"

git add -A

read -p "Please enter the commit message : " message
git commit -am "$message"

git push origin master
